### PR TITLE
CI Separate browser installation into a composite workflow NFC

### PR DESCRIPTION
**Pull request by ryanking13**
This separates browser installation steps into a composite workflow, so it can be reused in other yaml files.

### CODE REVIEW

**Comment by joemarshall** [comment]
I think this breaks if you call it from another repo. Annoyingly if main.yaml is loaded from another repo, all the checkout information is that of the calling repo. 

This actually needs fixing for testall.yaml also, it currently fails from other repos.

Sensible options are:
1) Make it explicitly checkout the `pyodide-test` repo into a sub-directory and call things from there. Downside of that is that you either a)get the latest checkout of pyodide-test, or b) you use a fixed version tag, or c) you do something mad with github actions to add an extra commit after each successful commit which inserts the right tags into main.yaml and testall.yaml

2) Move the browser install action into a separate `pyodide/install-test-browsers` action repository and then call it just like any other action.

**Comment by ryanking13** [comment]
> I think this breaks if you call it from another repo. Annoyingly if main.yaml is loaded from another repo, all the checkout information is that of the calling repo.

Oh, okay... that makes sense. Thanks.

> Move the browser install action into a separate pyodide/install-test-browsers action repository and then call it just like any other action.

@rth would it be okay to make a separate repository (e.g. `pyodide/actions`) so we can store common GHA actions that can be used in multiple repositories in the Pyodide organization?

**Comment by rth** [comment]
Yes, sure maybe `pyodide/pyodide-actions` so when you fork it it's not just called `<username>/actions`

**Comment by ryanking13** [comment]
Thanks! I created [pyodide/pyodide-actions](https://github.com/pyodide/pyodide-actions).

**Comment by ryanking13** [comment]
Opened #70 using `pyodide/pyodide-actions`.

**Pull request closed without merging**
