### PR TITLE
Remove ctypes so it can work with no dynamic linking builds

### PR DESCRIPTION
**Pull request by hoodmane**

### CODE REVIEW

**Review by ryanking13 — APPROVED** [review]
Thanks, @hoodmane! Maybe for no-dynamic-linking build, ctype need be statically linked. But that would require a large work and this PR is fine as-is.

**Comment by hoodmane** [comment]
ctypes is statically linked the problem is that it uses dlsym at runtime.

**Comment by hoodmane** [comment]
Thanks @ryanking13!

**Comment by ryanking13** [comment]
> ctypes is statically linked the problem is that it uses dlsym at runtime.

Oh, right. I got confused that I thought we were unvendering ctypes.

**Pull request merged**
