### PR TITLE
Workaround for ast.fix_mising_locations bug in python3.11

### PR DESCRIPTION
**Pull request by hoodmane**

### CODE REVIEW

**Comment by rth** [comment]
Safari CI is failing.

**Comment by hoodmane** [comment]
Error is `pytest: command not found`. Looks unrelated?

**Comment by hoodmane** [comment]
I think that Python 3.11's `ast.fix_missing_locations` has a bug. Or possibly the bug was always there but the compiler notices and gets angry now.

**Comment by ryanking13** [comment]
> Error is `pytest: command not found`. Looks unrelated?

Yeah, it doesn't seem related to this PR, I guess we can fix that in a separate PR. Probably it is related to [this](https://github.blog/changelog/2022-10-03-github-actions-jobs-running-on-macos-latest-are-now-running-on-macos-12/)?

**Comment by rth** [comment]
Sounds, good. Indeed I also fails on maion now after I restarted CI there.

**Comment by hoodmane** [comment]
I guess someone should minimize the bug here and report it to cpython **sigh**

**Pull request merged**
