### PR TITLE
[doc] Update README.md

### LINKED ISSUE #99: [doc] Copy file to pyodide gives TypeError: 'module' object is not callable
The [docs](https://github.com/pyodide/pytest-pyodide#copying-files-to-pyodide) suggests using a `copy_files_to_pyodide` decorator but the suggested (simplified) line throws an error:

```py
from pytest_pyodide import copy_files_to_pyodide, run_in_pyodide

@copy_files_to_pyodide(file_list=["hello.txt"])
@run_in_pyodide
def test_add(selenium):
    assert 1+1 == 2
```

> TypeError: 'module' object is not callable

So there could be a problem with the documentation.

Now if I try to use the `copy_files_to_emscripten_fs` from the module I get a `NameError`

```py
from pytest_pyodide import copy_files_to_pyodide, run_in_pyodide

@run_in_pyodide
@copy_files_to_pyodide.copy_files_to_emscripten_fs(file_list=["hello.txt"], selenium=selenium)
def test_add(selenium):
    assert 1+1 == 2
```

> NameError: name 'selenium' is not defined

No matter if I place the decorator before or after `run_in_pyodide`. 

What's the correct way to copy files?

### PR DESCRIPTION
**Pull request by fcrozatier**
Document where to import `copy_files_to_pyodide` from
fixes #99

### CODE REVIEW

**Review by rth — APPROVED** [review]
Thanks @fcrozatier !

**Comment by rth** [comment]
BTW, minor point, does anyone know why we now need to manually approve the CI before it is run? Is it expected or something is misconfigured?

**Comment by ryanking13** [comment]
> BTW, minor point, does anyone know why we now need to manually approve the CI before it is run? Is it expected or something is misconfigured?

I think it is expected.

https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/

**Comment by ryanking13** [comment]
The CI failure is not related to this PR. Probably we need to port https://github.com/pyodide/pyodide/pull/3956 to pytest-pyodide?

**Pull request merged**
