### PR TITLE
Add support for custom headers in the pytest web server code

### PR DESCRIPTION
**Pull request by joemarshall**
This allows you to spawn custom servers which send different headers, for tests of networking things. Putting this into pytest_pyodide would mean pyodide-http wouldn't need to copy/paste all the server code across to its tests any more. Or anything else that uses cross-site isolation could also test with this.

You can also override the main server if you create a new web_server_main fixture, so that it sends e.g. headers to enable cross site isolation if you use threads, like so:

```py
# this fixture runs everything twice, once with cross-site isolation enabled 
# (so you can use atomics and sharedarraybuffer), once with it disabled 
# (so you can see what happens in the non-isolated fallback code)
@fixture(scope="session", params=["isolated", "non-isolated"])
def web_server_main(request):
    """Web server that serves files in the dist directory"""
    if request.param == "isolated":
        headers = {"x-mylovelyheader": "123", "Cross-Origin-Opener-Policy": "same-origin",
                   "Cross-Origin-Embedder-Policy": "require-corp"}
    else:
        headers = {"x-mylovelyheader": "123"}
    with spawn_web_server_custom(request.config.option.dist_dir, headers) as output:
        yield output
```

### CODE REVIEW

**Review by ryanking13 — APPROVED** [review]
Thanks, @joemarshall! It looks good to me. Please update the [changelog](https://github.com/pyodide/pytest-pyodide/blob/main/CHANGELOG.md).

@koenvo Are you interested in reviewing this?

**Comment by koenvo** [comment]
This might be a nice opportunity to add a test for the spawn web server function. And especially the access control expose headers is important to test. I’m not totally sure what happens if you send access control expose headers for standard headers.

The tests can also be a good starting point for me to add request logging

**Comment by ryanking13** [comment]
> This might be a nice opportunity to add a test for the spawn web server function. And especially the access control expose headers is important to test. I’m not totally sure what happens if you send access control expose headers for standard headers.
> 
> The tests can also be a good starting point for me to add request logging

Yes, that sounds good to me.

**Comment by rth** [comment]
I added a changelog entry and a unit test (also to check access control headers as suggested above). Will merge on green CI.

**Pull request merged**
