### PR TITLE
Add request handler spawn web server

### PR DESCRIPTION
**Pull request by koenvo**
This PR makes it possible to pass a different `Handler` to be used in the webserver. 

With a different `Handler` in place a test can for example:
1. Return custom headers (related to https://github.com/pyodide/pytest-pyodide/pull/39)
2. Echo the original request (related to https://github.com/koenvo/pyodide-http/pull/16)
3. Catch all requests (related to https://github.com/pyodide/pytest-pyodide/issues/41)

Side note: this PR includes https://github.com/pyodide/pytest-pyodide/pull/46

[edit] Still need to figure out how to get `fetch` or `pyodide.http` working for node.

### CODE REVIEW

**Comment by ryanking13** [comment]
> [edit] Still need to figure out how to get `fetch` or `pyodide.http` working for node.

Maybe use `pyfetch` instead of `open_url` in test?

**Comment by nicornk** [comment]
@koenvo Will this also allow me to answer POST requests?

**Comment by koenvo** [comment]
Jup. I need this myself to test pyodide-http post requests :-)

let me copy the test as an example. For sync posts it requires some more Cors headers than for async but I’ll add that in the comments as well

**Comment by nicornk** [comment]
@koenvo I was trying to contribute some fixes to pyodide-http and failed as well.
Thanks for adding this here, this will make it easier to create test cases for pyodide-http!

**Comment by koenvo** [comment]
I'm having a hard time with a node test. It seems `node-fetch` sends a GET request instead of a POST request in the `test_post_handler` test.
After adding a '400 Bad Request' to the `EchoHandler` (https://github.com/pyodide/pytest-pyodide/pull/47/commits/c9f22e18e0f87c4d90470296cb81255d800e5e63) the test shows a '400' error instead of '404' (in previous tests).

**Comment by rth** [comment]
@koenvo Do we actually need to test this from within pyodide?  I think  testing the web server with `urllib.request.urlopen` as I did in https://github.com/pyodide/pytest-pyodide/pull/39 would be sufficient and much easier. It doesn't really matter from where requests are made.

Would you mind resolving conflicts and moving your test to `tests/test_server.py`? Thanks!

**Comment by koenvo** [comment]
> @koenvo Do we actually need to test this from within pyodide? I think testing the web server with `urllib.request.urlopen` as I did in #39 would be sufficient and much easier. It doesn't really matter from where requests are made.
> 
> Would you mind resolving conflicts and moving your test to `tests/test_server.py`? Thanks! Otherwise I can make these changes.

Very good point. Updated the PR.

**Review by ryanking13 — APPROVED** [review]
LGTM, thanks! Could you please update the [changelog](https://github.com/pyodide/pytest-pyodide/blob/main/CHANGELOG.md)?.

**Comment by rth** [comment]
Thanks @koenvo !

**Pull request merged**
