### PR TITLE
Publish to PyPI

### LINKED ISSUE #6: Document usage
It would be good to document  usage, with something like,
 - downloading the pyodide dist
 - using the included fixtures

Maybe in the readme for a start

### PR DESCRIPTION
**Pull request by rth**
- Adds minimal "how to use" description in the readme (closes #6 )
 - Enables setuptools_scm to get the version from the git tag. For release one only need to tag (there is no need to manually specify version). 
 - Add CI setup to publish to PyPI. @ryanking13 please remind me your PyPI username, I'll add to there. 

For now, I just uploaded a test version to make sure the rendering is OK https://pypi.org/project/pytest-pyodide/. 

I'm not really sure what we should do about versions:
 a) either we make the versioning be completely independent and start say with 0.1.0
 b) or we try to follow Pyodide versions but then it means we can't easily use semver

In any case, version x of this package would likely work only with some range of pyodide versions (at least those that we check in CI).

### CODE REVIEW

**Review by ryanking13 — APPROVED** [review]
Thanks!

> I'm not really sure what we should do about versions:
> a) either we make the versioning be completely independent and start say with 0.1.0
> b) or we try to follow Pyodide versions but then it means we can't easily use semver

It would be nice to use the option 'a' in the long term. But Pyodide API is very vulnerable to change yet, so I'm +1 with the option 'b' for now.

Perhaps we can use {pyodide-stable-version}.{pytest-pyodide-version}, in order to tell that it is compatible with a specific Pyodide version. e.g. `0.21.0.1`, `0.21.0.2`, ....

> Add CI setup to publish to PyPI. @ryanking13 please remind me your PyPI username, I'll add to there.

Thanks! It's `sihadan` (I should unify my usernames someday...).

**Comment by rth** [comment]
Thanks for the review!

> Perhaps we can use {pyodide-stable-version}.{pytest-pyodide-version}

Well, that would not be a valid Python version https://peps.python.org/pep-0440/#version-scheme. OK let's go with 0.21.0 for now and we can switch to something else (e.g. 1.0.0) in the future

**Comment by rth** [comment]
OK, actually the deploy job still does seem to be failing with no error message https://github.com/pyodide/pytest-pyodide/runs/7423961479?check_suite_focus=true . Will do another PR to fix.

**Comment by ryanking13** [comment]
> OK, actually the deploy job still does seem to be failing with no error message https://github.com/pyodide/pytest-pyodide/runs/7423961479?check_suite_focus=true . Will do another PR to fix.

image

Here is the error message from the summary

**Comment by ryanking13** [comment]
> Well, that would not be a valid Python version https://peps.python.org/pep-0440/#version-scheme.

`0.0.0.0` is a valid python version since Release segment of pep 440 is `N(.N)*`. Anyway, 0.21.0 also looks fine to me.

**Pull request merged**
